name: prerelease
on: 
  push
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Test read-yaml
    outputs:
      goVersions: ${{ steps.versions.outputs.goVersions }}
    steps:
      - uses: actions/checkout@v1
      - name: Run read-yaml action
        id: yaml-data
        uses: KJ002/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: './build.yml'          # File to read from
          key-path: '["goVersions"]' # Access the runs key then the using key and retuns the value.
      - run: echo ${{ steps.yaml-data.outputs.data }}
      - name: save output
        id: versions
        run: echo '::set-output name=goVersions::${{ steps.yaml-data.outputs.data }}'
  job-middle:
    runs-on: ubuntu-latest
    needs: job1
    steps: 
      - run: echo ${{ fromJSON(needs.job1.outputs.goVersions) }}
  job2: 
    name: the matrix
    needs: job1
    strategy:
      matrix:
        goVersion: ${{ fromJSON(needs.job1.outputs.goVersions) }}
        distro: ["macos-latest", "ubuntu-latest"]
    runs-on: ${{ matrix.distro }}
    steps:
      - name: print stuff
        run: echo ${{ matrix.goVersion}}
    


