name: test
on: [push]
jobs:
  job1:
    name: Modify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: inspect files
        run: ls -la
