name: test
on:
  push: 
    tags:
     - *
jobs:
  job1:
    name: Modify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: tag name
        run: echo "TAG NAME = ${ GITHUB_REF#refs/*/ }"
      - name: echo ${ GITHUB_REF#refs/*/ } > README.md
      - name: inspect README
        run: cat README.md
